---
layout:  post
title: "Hello World: Static and Interactive Visualizations!"
comments:  true
published:  true
author: "Sebastian Perez Saaibi"
date: "2016-01-05"
categories: [R, "htmlwidgets", "visualization"]
output:
  html_document:
    mathjax:  default
    fig_caption:  true
---


Hi!
This is my first post. Here I'm just interested in exploring how to make some simple (but cool) plots, both static and dynamic using R.

Enjoy the results (and interact with them).



```{r include = FALSE}
library(knitr)
library(ggplot2)
library(plotly)
library(ggthemes)
library(leaflet)
```

```{r,echo=FALSE, warning=FALSE, message= FALSE, results='asis'}
p <- ggplot(iris) + geom_point(aes(Sepal.Length,Sepal.Width, color = Species)) + theme_wsj() + ggtitle("Sepal Dimensions")
print(p)
```

```{r,echo=FALSE, warning=FALSE, message= FALSE, results='asis'}
p <- plot_ly(iris, x = Petal.Length, y = Petal.Width,
        color = Species, mode = "markers")
p
```


```{r,echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
library(forecast)
library(ggthemes)

ggplot(mtcars) + geom_point(aes(wt,qsec, color = cyl)) + theme_economist()
```

```{r,echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
 library(leaflet)
 
 m <- leaflet() %>%
   addTiles() %>%  # Add default OpenStreetMap map tiles
   addMarkers(lng = -0.07125, lat = 51.51895, 
              popup = "Reasonably Priced Stella Artois")
 m
```



